title: Christopher Obbard
description: I am the Chief Engineer at 64 Studio Ltd where we develop software and hardware solutions for clients involved with multimedia on Embedded platforms.
baseurl: ""
url: "http://obbard.me"
markdown: kramdown
